services:
  - type: web
    name: telegram-image-search
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false  # Set this manually in the Render dashboard
